identifier: oren.trainer_config.TrainerConfig
seed: 12345
log_dir: logs
exp_name: oren_ros
device: cuda
data:
    identifier: oren.dataset.data_config.DataConfig
    dataset_name: ros
    dataset_args:
        min_depth: 0.8
        max_depth: 40.0
    start_frame: 0
    end_frame: -1
bound_min: [-10, -10, -10] # will be overwritten by the dataset args
bound_max: [10, 10, 10] # will be overwritten by the dataset args
key_frame_set:
    identifier: oren.key_frame_set.KeyFrameSetConfig
    insert_method: intersection
    insert_interval: 50
    insert_ratio: 0.7
    frame_selection: multiple_max_set_coverage
    selection_window_size: 8
    frame_weight: uniform
model:
    identifier: oren.model.SdfNetworkConfig
    octree_cfg:
        identifier: oren.octree_config.OctreeConfig
        resolution: 0.7
        tree_depth: 8 # 0.7*2^8=112m
        semi_sparse_depth: 5
        init_voxel_num: 80000
        insertion_threshold: 3
        skip_insertion_if_exists: true # speed up a bit
        residual_feature_dim: 3
        residual_num_levels: 1
        gradient_augmentation: true
        independent_smallest_leaf_vertex: true
    residual_net_cfg:
        identifier: oren.residual_net.ResidualNetConfig
        mlp_activation: LeakyReLU
        hidden_dims: [32, 32]
        output_sdf_scale: 0.1
        input_feature_dim: 1
criterion:
    identifier: oren.criterion.CriterionConfig
    boundary_loss_weight: 100
    perturbation_loss_weight: 100
    eikonal_loss_surface_weight: 30
    eikonal_loss_perturbation_weight: 50
    eikonal_loss_space_weight: 100
    projection_loss_weight: 100
    boundary_loss_prior_weight: 100
    perturbation_loss_prior_weight: 100
    eikonal_loss_surface_prior_weight: 30
    eikonal_loss_perturbation_prior_weight: 50
    eikonal_loss_space_prior_weight: 100
    projection_loss_prior_weight: 100
    boundary_loss_type: L1
    perturbation_loss_type: L1
    eikonal_loss_type: L1
    projection_loss_type: L1
    perturbation_loss_exp_penalty: 1.0
    heat_loss_weight: 0.0
    heat_loss_lambda: 4.0
    sign_loss_free_weight: 0.0
    sign_loss_occ_weight: 0.0
    sign_loss_temperature: 100.0
num_init_frames: 3
init_frame_iterations: 10
num_iterations_per_frame: 1
num_rays_total: 20480
extra_surface_sample: false # not helpful
frame_downsample: 10
sample_rays:
    identifier: oren.utils.sampling.SampleRaysConfig
    n_stratified: 1
    n_perturbed: 2
    depth_min: 0.8
    depth_max: 40.0
    surface_margin: 1.44
    sigma_s: 0.48
batch_size: 204800
lr: 0.005
grad_method: finite_difference
finite_difference_eps: 0.03
final_iterations: 0
save_mesh: true
mesh_resolution: 0.2
mesh_iso_value: 0.0
clean_mesh: true
ckpt_interval: -1
profiling: false
profiling_verbose: false
