base_config: trainer-replica.yaml
data:
    dataset_name: replica
    dataset_args:
        data_path: data/replica
key_frame_set:
    insert_interval: 50
    selection_window_size: 8
model:
    octree_cfg:
        resolution: 0.1
        tree_depth: 8
        semi_sparse_depth: 5